apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-consumer
  template:
    metadata:
      labels:
        app: traffic-consumer
    spec:
      containers:
        - name: consumer
          image: traffic-prediction/consumer:latest
          envFrom:
            - configMapRef:
                name: traffic-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: models
              mountPath: /app/models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc
